import { expect, test } from 'bun:test'
import { calls, client, created, fresh, until, useHost } from '../host-fixture.test.ts'

useHost()

test('/queue lists in order, next steers a running turn, clear drops only queued messages', async () => {
	let a = client()
	let id = created(a)
	let b = client()
	b.conn.send({ type: 'open', sessionId: id })
	await until(() => b.views.has(id))
	let send = (text: string) => a.conn.send({ type: 'submit', sessionId: id, text })
	send('working')
	await until(() => calls.length === 1)
	send('/queue first')
	send('/queue second')
	await until(() => b.views.get(id)?.inbox.length === 2)
	send('/queue')
	await until(() => a.of('output').some((e) => e.text.includes('1. first\n2. second')))
	send('/queue next')
	await until(() => b.views.get(id)?.inbox.some((m) => m.text === 'first' && !m.queue))
	expect(b.views.get(id)?.inbox.map((m) => [m.text, m.queue])).toEqual([['first', undefined], ['second', true]])
	send('/queue clear')
	await until(() => b.views.get(id)?.inbox.length === 1)
	expect(a.of('output').at(-1)?.text).toContain('1 queued message')
	expect((await fresh(id)).inbox.map((m) => m.text)).toEqual(['first'])
	calls[0]!.push({ type: 'done', reason: 'end' })
	await until(() => calls.length === 2)
	expect(calls[1]!.input.messages.at(-1).blocks[0].text).toContain('first')
})

test('/queue next starts the oldest as a new turn when no turn is running', async () => {
	let a = client()
	let id = created(a)
	let send = (text: string) => a.conn.send({ type: 'submit', sessionId: id, text })
	send('working')
	await until(() => calls.length === 1)
	send('/queue later')
	await until(() => a.views.get(id)?.inbox.length === 1)
	a.conn.send({ type: 'pause', sessionId: id })
	await until(() => a.views.get(id)?.state.type === 'paused')
	send('/queue next')
	await until(() => calls.length === 2)
	expect(a.views.get(id)?.inbox).toEqual([])
	expect(calls[1]!.input.messages.at(-1).blocks[0].text).toContain('later')
})
