// Human and model renames share the same command and history path.
import type { SlashCommand } from '../commands.ts'
import { names } from '../../common/names.ts'
import { sessions } from '../sessions.ts'

export const command: SlashCommand = {
	help: () => '/rename <name>: set the session title. No argument (or auto): clear to a placeholder. Titles may later follow topic drift.',
	async run(args, _answers, ctx) {
		let text = args.trim()
		let previous = sessions.open(ctx.sessionId).name
		if (text === 'backfill') {
			return { say: 'Session titles are generated by the conversation model; backfill does not copy prompts into titles.' }
		}
		if (!text || text === 'auto') {
			ctx.setName!(undefined)
			return { say: `/rename: ${previous} → ${sessions.open(ctx.sessionId).name}` }
		}
		try {
			let name = names.validate(text)
			ctx.setName!(name)
			return { say: `/rename: ${previous} → ${name}` }
		} catch (e) { return { error: (e as Error).message } }
	},
}
