import { expect, test } from 'bun:test'
import { blocks, type Block } from './blocks.ts'

function stripAnsi(s: string): string {
	return s.replace(/\x1b\[[0-9;?]*[a-zA-Z]/g, '').replace(/\r/g, '')
}

function headerLine(lines: string[]): string {
	return lines.map(stripAnsi).find((line) => line.trim()) ?? ''
}

function contentLines(lines: string[]): string[] {
	const clean = lines.map(stripAnsi)
	let start = clean.findIndex((line) => line.trim()) + 1
	const end = clean.at(-1)?.trim() ? clean.length : clean.length - 1
	if (!clean[start]?.trim()) start++
	return clean.slice(start, end)
}

test('spawn_agent block renders full input args', () => {
	const block: Block = {
		type: 'tool',
		name: 'spawn_agent',
		toolId: 'call_123',
		input: {
			task: 'Design the benchmark prompt\nKeep it concise.',
			mode: 'fresh',
			model: 'openai/gpt-5.4',
			cwd: '/Users/antti/.hal',
			title: 'edit benchmark prompt',
			kind: 'subagent',
		},
		output: 'Queued subagent spawn from 04-lfp',
	}

	const rendered = blocks.renderBlock(block, 100)
	const lines = rendered.map((l) => stripAnsi(l))
	const header = lines.find((line) => line.trim()) ?? ''
	const body = lines.slice(1).join('\n')

	expect(rendered.join('\n')).not.toContain('\x1b[2m')
	expect(header).toContain('Spawn agent')
	expect(body).toContain('task: `Design the benchmark prompt')
	expect(body).toContain("mode: 'fresh'")
	expect(body).toContain("model: 'openai/gpt-5.4'")
	expect(body).toContain("cwd: '/Users/antti/.hal'")
	expect(body).toContain("title: 'edit benchmark prompt'")
	expect(body).toContain("kind: 'subagent'")
	expect(body).toContain('Queued subagent spawn from 04-lfp')
})

test('send block renders target session and message text', () => {
	const block: Block = {
		type: 'tool',
		name: 'send',
		input: {
			sessionId: '33-270',
			text: 'Stop. Do not do any analysis or file access.',
			queue: false,
		},
		output: 'Sent message to tab 4 (33-270)',
	}

	const lines = blocks.renderBlock(block, 100).map((l) => stripAnsi(l))
	const header = lines.find((line) => line.trim()) ?? ''
	const body = lines.slice(1).join('\n')

	expect(header).toContain('Send to tab 4 (33-270)')
	expect(body).toContain('Stop. Do not do any analysis or file access.')
	expect(body).toContain('Sent message to tab 4 (33-270)')
})

test('grep block quotes its search pattern in header', () => {
	const block: Block = {
		type: 'tool',
		name: 'grep',
		input: { pattern: 'const MODEL_GROUPS', path: '/Users/antti/.hal/src' },
	}

	const header = headerLine(blocks.renderBlock(block, 100))
	expect(header).toContain('Grep "const MODEL_GROUPS" in /Users/antti/.hal/src')
})

test('eval block separates returned output from code', () => {
	const block: Block = {
		type: 'tool',
		name: 'eval',
		input: { code: 'let count = 0\nif (count === 0) {\n\treturn count\n}' },
		output: '0',
	}

	const body = contentLines(blocks.renderBlock(block, 100))
	expect(body).toEqual([
		' let count = 0',
		' if (count === 0) {',
		' \treturn count',
		' }',
		' Result:',
		' 0',
	])
})

test('eval block omits result separator when there is no returned output', () => {
	const block: Block = {
		type: 'tool',
		name: 'eval',
		input: { code: 'let count = 0' },
	}

	const body = contentLines(blocks.renderBlock(block, 100))
	expect(body).toEqual([' let count = 0'])
})

test('bash block still uses continuation backslashes for multiline commands', () => {
	const block: Block = {
		type: 'tool',
		name: 'bash',
		input: { command: 'echo one\necho two' },
	}

	const body = contentLines(blocks.renderBlock(block, 100))
	expect(body).toEqual([' echo one \\', ' echo two'])
})

test('bash block strips redundant cd prefix for the current cwd', () => {
	const block: Block = {
		type: 'tool',
		name: 'bash',
		input: { command: 'cd /Users/antti/.hal && git status', cwd: '/Users/antti/.hal/' },
	}

	const header = headerLine(blocks.renderBlock(block, 100))
	expect(header).toContain('Bash: git status')
	expect(header).not.toContain('cd /Users/antti/.hal')
})

test('read blob block header names the source blob', () => {
	const block: Block = {
		type: 'tool',
		name: 'read_blob',
		input: { id: '04-fyx/0gdec4-bol' },
		output: 'blob data',
	}

	const header = headerLine(blocks.renderBlock(block, 100))
	expect(header).toContain('Read blob 04-fyx/0gdec4-bol')
})
test('bash git commit renders rich commit details instead of shell plumbing', () => {
	const block: Block = {
		type: 'tool',
		name: 'bash',
		input: { command: 'cd /Users/antti/.hal && git commit -m "Nice title\n\nGenerated by test"', cwd: '/Users/antti/.hal' },
		output: `[main abc123] Nice title
[hal-commit]
{
	branch: 'main',
	hash: 'abc123',
	message: 'Nice title\n\nGenerated by test',
	summary: '2 files changed, 3 insertions(+), 1 deletion(-)',
	files: [
		{ path: 'src/a.test.ts', added: 2, removed: 0, locDelta: 1, isCode: false },
		{ path: 'src/a.ts', added: 1, removed: 1, locDelta: 0, isCode: true }
	],
	locDelta: 1,
	locDeltaCode: 0
}
[/hal-commit]`,
	}

	const raw = blocks.renderBlock(block, 100)
	const lines = raw.map((l) => stripAnsi(l))
	expect(headerLine(raw)).toContain('Commit abc123: Nice title')
	expect(lines).toContain(' Generated by test')
	expect(lines).toContain(' main abc123 · 2 files changed, 3 insertions(+), 1 deletion(-)')
	expect(lines).toContain(' Tests / docs / other')
	expect(lines).toContain('    2 −0   src/a.test.ts')
	expect(lines).toContain(' Code')
	expect(lines).toContain('    1 −1   src/a.ts  0 loc')
	expect(lines).toContain(' LOC: 0 (with tests, +1)')
	expect(raw.join('\n')).toContain('\x1b[1m0\x1b[22m')
	expect(lines.join('\n')).not.toContain('[main abc123]')
	expect(lines.join('\n')).not.toContain('cd /Users/antti/.hal')
})

test('commit block outside the Hal repo lists files without LOC framing', () => {
	// Foreign repos carry no locDelta/isCode, so there is no code-vs-test split
	// and no LOC total to show.
	const block: Block = {
		type: 'tool',
		name: 'bash',
		input: { command: 'git commit -m "add main"' },
		output: `[main 5ba831a] add main
[hal-commit]
{
	branch: 'main',
	hash: '5ba831a',
	message: 'add main',
	summary: '1 file changed, 3 insertions(+)',
	files: [
		{ path: 'main.py', added: 3, removed: 0 }
	]
}
[/hal-commit]`,
	}

	const lines = blocks.renderBlock(block, 100).map((l) => stripAnsi(l))
	expect(lines).toContain(' main 5ba831a · 1 file changed, 3 insertions(+)')
	expect(lines).toContain('    3 −0   main.py')
	expect(lines.join('\n')).not.toContain('LOC:')
	expect(lines.join('\n')).not.toContain('Tests / docs / other')
	expect(lines.join('\n')).not.toContain('Code')
})

test('bash git commit -F renders from metadata message', () => {
	const block: Block = {
		type: 'tool',
		name: 'bash',
		input: { command: "git commit -F - <<'EOF'\nFile title\n\nFile body\nEOF" },
		output: `[main def456] File title
[hal-commit]
{
	branch: 'main',
	hash: 'def456',
	message: 'File title\n\nFile body',
	summary: '1 file changed, 1 insertion(+)',
	files: [
		{ path: 'src/a.ts', added: 1, removed: 0, locDelta: 1, isCode: true }
	],
	locDelta: 1,
	locDeltaCode: 1
}
[/hal-commit]`,
	}

	const lines = blocks.renderBlock(block, 100).map((l) => stripAnsi(l))
	expect(lines.find((line) => line.trim()) ?? '').toContain('Commit def456: File title')
	expect(lines).toContain(' File body')
	expect(lines).toContain(' main def456 · 1 file changed, 1 insertion(+)')
	expect(lines.join('\n')).not.toContain('[hal-commit]')
	expect(lines.join('\n')).not.toContain('git commit -F')
})

test('bash git commit --amend marks commit block as amend', () => {
	const block: Block = {
		type: 'tool',
		name: 'bash',
		input: { command: "cat > /tmp/msg <<'EOF'\nAmended title\nEOF\ngit commit --amend -F /tmp/msg" },
		output: `[main fed789] Amended title
[hal-commit]
{
	branch: 'main',
	hash: 'fed789',
	message: 'Amended title',
	summary: '1 file changed, 1 insertion(+)',
	files: [
		{ path: 'src/a.ts', added: 1, removed: 0, locDelta: 1, isCode: true }
	],
	locDelta: 1,
	locDeltaCode: 1
}
[/hal-commit]`,
	}

	const lines = blocks.renderBlock(block, 100).map((l) => stripAnsi(l))
	const header = lines.find((line) => line.trim()) ?? ''
	expect(header).toContain('Amend fed789: Amended title')
	expect(header).not.toContain('Commit fed789')
})

test('failed shell-substitution commit renders as ordinary bash', () => {
	const block: Block = {
		type: 'tool',
		name: 'bash',
		input: { command: "git commit -m \"$(cat <<'EOF'\nBad title\nEOF\n)\"" },
		output: 'bash: unexpected EOF while looking for matching `\'\'\n',
	}

	const lines = blocks.renderBlock(block, 100).map((l) => stripAnsi(l))
	const header = lines.find((line) => line.trim()) ?? ''
	expect(header).toContain('Bash')
	expect(header).not.toContain('Commit')
	expect(lines.join('\n')).toContain("git commit -m")
	expect(lines.join('\n')).toContain('bash: unexpected EOF')
})

test('edit block header shows affected hashline refs', () => {
	const block: Block = {
		type: 'tool',
		name: 'edit',
		input: {
			path: 'src/app.ts',
			operation: 'replace',
			start_ref: '12:abc',
			end_ref: '15:def',
			new_content: 'next',
		},
	}

	const header = headerLine(blocks.renderBlock(block, 100))
	expect(header).toContain('Edit src/app.ts (12:abc-15:def)')
})

test('edit block shows hashline refs for debugging', () => {
	const block: Block = {
		type: 'tool',
		name: 'edit',
		input: {
			path: 'src/app.ts',
			operation: 'replace',
			start_ref: '12:abc',
			end_ref: '15:def',
			new_content: 'next',
		},
	}

	const body = blocks
		.renderBlock(block, 100)
		.map((l) => stripAnsi(l))
		.slice(1)
		.join('\n')
	expect(body).toContain("operation: 'replace'")
	expect(body).toContain("start_ref: '12:abc'")
	expect(body).toContain("end_ref: '15:def'")
})

test('edit block keeps failure details visible after diff preview', () => {
	const block: Block = {
		type: 'tool',
		name: 'edit',
		output: [
			'--- before',
			'2:aaa old line',
			'',
			'+++ after',
			'2:bbb new line',
			'',
			'TypeScript check failed for src/app.ts:',
			'error TS2322: Type string is not assignable to number.',
		].join('\n'),
	}

	const body = blocks
		.renderBlock(block, 100)
		.map((l) => stripAnsi(l))
		.slice(1)
		.join('\n')
	expect(body).toContain('− 2:aaa old line')
	expect(body).toContain('+ 2:bbb new line')
	expect(body).toContain('TypeScript check failed for src/app.ts:')
	expect(body).toContain('error TS2322: Type string is not assignable to number.')
})
