// Bash tool — shell command execution.
//
// Runs commands via bash -lc with configurable timeout, output capture,
// and 1MB output limit with middle-truncation.

import { resolve } from 'path'
import { homedir } from 'os'
import { toolRegistry, type Tool, type ToolContext } from './tool.ts'
import { helpers } from '../utils/helpers.ts'
import { processOutput } from '../utils/process-output.ts'
import { sensitive } from './sensitive.ts'
import { ason } from '../utils/ason.ts'
import { cloc } from '../utils/cloc.ts'

const config = {
	/** Default timeout in milliseconds. */
	defaultTimeout: 120_000,
	/** Maximum output size in bytes before truncation. */
	maxOutputBytes: 1_000_000,
}

interface BashInput {
	command?: string
	timeout?: number
}

type TimerWithUnref = ReturnType<typeof setTimeout> & { unref?: () => void }

interface CommitFileStat {
	path: string
	added: number
	removed: number
	locDelta: number
	isCode: boolean
}

interface CommitMetadata {
	branch: string
	hash: string
	message: string
	summary: string
	files: CommitFileStat[]
	locDelta: number
	locDeltaCode: number
}

const COMMIT_META_START = '[hal-commit]'
const COMMIT_META_END = '[/hal-commit]'

const HOME = homedir()

function shellPath(text: string, cwd: string): string {
	let path = text.replace(/^['"]|['"]$/g, '')
	if (path === '~') path = HOME
	if (path.startsWith('~/')) path = HOME + path.slice(1)
	return resolve(cwd, path)
}

function stripCdCwd(command: string | undefined, cwd: string): string | undefined {
	const match = command?.match(/^cd\s+(.+?)\s*&&\s*/)
	if (!match) return command
	const target = shellPath(match[1]!, cwd)
	return target === resolve(cwd) ? command!.slice(match[0].length) : command
}

function rewriteHalCommitMessageNewlines(command: string): string {
	if (!command.includes('\\n') || !isCommitCommand(command)) return command

	// The model often writes `-m "body\\n\\nGenerated..."`; bash passes that
	// literally, then the model amends the commit to fix its message. Convert only
	// Hal's generated commit-message footer before spawning git so the first
	// commit is already correct.
	let out = command.replace(/((?:^|\s)(?:-m|--message)(?:=|\s+))"([^"]*\\n[^"]*Generated by hal\/[^"]*)"/g, (_all, prefix: string, message: string) => {
		return `${prefix}"${message.replaceAll('\\n', '\n')}"`
	})
	out = out.replace(/((?:^|\s)(?:-m|--message)(?:=|\s+))'([^']*\\n[^']*Generated by hal\/[^']*)'/g, (_all, prefix: string, message: string) => {
		return `${prefix}'${message.replaceAll('\\n', '\n')}'`
	})
	return out
}

function isCommitCommand(command: string): boolean {
	return /\bgit\s+commit\b/.test(command)
}

function isTestPath(path: string): boolean {
	return path.includes('.test.') || path.includes('.spec.') || path.startsWith('test/') || path.startsWith('tests/') || path.includes('/test/') || path.includes('/tests/')
}

function isCodePath(path: string): boolean {
	return /\.[jt]sx?$/.test(path) && !isTestPath(path)
}

function plural(n: number, one: string, many: string): string {
	return n === 1 ? one : many
}

function commitSummary(files: CommitFileStat[]): string {
	let added = 0
	let removed = 0
	for (const file of files) {
		added += file.added
		removed += file.removed
	}
	const parts = [`${files.length} ${plural(files.length, 'file', 'files')} changed`]
	if (added > 0) parts.push(`${added} ${plural(added, 'insertion', 'insertions')}(+)`)
	if (removed > 0) parts.push(`${removed} ${plural(removed, 'deletion', 'deletions')}(-)`)
	return parts.join(', ')
}

function runGit(cwd: string, args: string[]): string {
	const proc = Bun.spawnSync(['git', ...args], {
		cwd,
		stdout: 'pipe',
		stderr: 'ignore',
	})
	if ((proc.exitCode ?? 1) !== 0) return ''
	return new TextDecoder().decode(proc.stdout).trim()
}

function changedFiles(cwd: string): CommitFileStat[] {
	const numstat = runGit(cwd, ['diff-tree', '--root', '--no-commit-id', '--numstat', '-r', 'HEAD'])
	const patch = runGit(cwd, ['show', '--format=', '--unified=0', '--no-ext-diff', 'HEAD'])
	const changes = changedPatchLines(patch)
	const files: CommitFileStat[] = []
	for (const line of numstat.split('\n')) {
		if (!line.trim()) continue
		const parts = line.split('\t')
		const added = Number(parts[0])
		const removed = Number(parts[1])
		const path = parts.at(-1) ?? ''
		const locAdded = cloc.countText((changes.added.get(path) ?? []).join('\n'))
		const locRemoved = cloc.countText((changes.removed.get(path) ?? []).join('\n'))
		files.push({
			path,
			added: Number.isFinite(added) ? added : 0,
			removed: Number.isFinite(removed) ? removed : 0,
			locDelta: locAdded - locRemoved,
			isCode: isCodePath(path),
		})
	}
	return files
}

function changedPatchLines(patch: string): { added: Map<string, string[]>; removed: Map<string, string[]> } {
	const added = new Map<string, string[]>()
	const removed = new Map<string, string[]>()
	let path = ''
	for (const line of patch.split('\n')) {
		if (line.startsWith('--- a/') || line.startsWith('+++ b/')) {
			path = line.slice(6)
			if (!added.has(path)) added.set(path, [])
			if (!removed.has(path)) removed.set(path, [])
			continue
		}
		if (!path || line.startsWith('+++') || line.startsWith('---')) continue
		if (line.startsWith('+')) added.get(path)!.push(line.slice(1))
		if (line.startsWith('-')) removed.get(path)!.push(line.slice(1))
	}
	return { added, removed }
}

function commitMetadata(cwd: string): CommitMetadata | null {
	const hash = runGit(cwd, ['show', '-s', '--format=%h', 'HEAD'])
	if (!hash) return null
	const branch = runGit(cwd, ['branch', '--show-current']) || 'HEAD'
	const message = runGit(cwd, ['show', '-s', '--format=%B', 'HEAD'])
	const files = changedFiles(cwd)
	let locDelta = 0
	let locDeltaCode = 0
	for (const file of files) {
		locDelta += file.locDelta
		if (file.isCode) locDeltaCode += file.locDelta
	}
	return { branch, hash, message, summary: commitSummary(files), files, locDelta, locDeltaCode }
}

function appendCommitMetadata(out: string, command: string, cwd: string, code: number): string {
	if (code !== 0 || !isCommitCommand(command)) return out
	const meta = commitMetadata(cwd)
	if (!meta) return out
	return `${out}\n${COMMIT_META_START}\n${ason.stringify(meta, 'long')}\n${COMMIT_META_END}`
}

function normalizeInput(input: unknown, cwd: string): BashInput {
	const raw = toolRegistry.inputObject(input)
	const timeout = Number(raw.timeout)
	const command = typeof raw.command === 'string' ? raw.command : raw.command === undefined ? undefined : String(raw.command)
	return {
		command: stripCdCwd(command, cwd),
		timeout: Number.isFinite(timeout) ? timeout : undefined,
	}
}

// ── Process tree management ──

/** Get child PIDs of a process (non-recursive). */
function childPids(parentPid: number): number[] {
	const result = Bun.spawnSync(['pgrep', '-P', String(parentPid)], {
		stdout: 'pipe',
		stderr: 'ignore',
	})
	if (result.exitCode !== 0) return []
	const text = new TextDecoder().decode(result.stdout).trim()
	if (!text) return []
	return text
		.split(/\s+/)
		.map(Number)
		.filter((pid) => Number.isInteger(pid) && pid > 0)
}

/** Recursively kill a process tree. */
function killProcessTree(rootPid: number, signal: 'SIGTERM' | 'SIGKILL'): void {
	for (const pid of childPids(rootPid)) killProcessTree(pid, signal)
	try {
		process.kill(rootPid, signal)
	} catch {}
}

// ── Output truncation ──

function truncateOutput(text: string): string {
	return helpers.truncateUtf8(text, config.maxOutputBytes, '\n[… truncated]')
}

// ── Execution ──

async function execute(input: unknown, ctx: ToolContext): Promise<string> {
	const spec = normalizeInput(input, ctx.cwd)
	let command = spec.command ?? ''
	if (!command.trim()) return 'error: empty command'
	if (!ctx.approvedRisk && sensitive.commandMentionsProtectedPath(command)) return 'error: refusing to run command that mentions protected credentials file'
	command = rewriteHalCommitMessageNewlines(command)

	const timeout = spec.timeout ?? config.defaultTimeout

	const proc = Bun.spawn(['bash', '-lc', command], {
		cwd: ctx.cwd,
		stdout: 'pipe',
		stderr: 'pipe',
		env: { ...process.env, TERM: 'dumb' },
	})

	// Kill the full process tree on abort (SIGTERM, then SIGKILL after 2s)
	let abortCleanup: (() => void) | undefined
	if (ctx.signal) {
		const onAbort = () => {
			killProcessTree(proc.pid, 'SIGTERM')
			const timer: TimerWithUnref = setTimeout(() => killProcessTree(proc.pid, 'SIGKILL'), 2000)
			timer.unref?.()
		}
		if (ctx.signal.aborted) {
			onAbort()
		} else {
			ctx.signal.addEventListener('abort', onAbort, { once: true })
			abortCleanup = () => ctx.signal!.removeEventListener('abort', onAbort)
		}
	}

	// Set up timeout: kill process tree after timeout ms
	const timer = setTimeout(() => {
		killProcessTree(proc.pid, 'SIGTERM')
		setTimeout(() => killProcessTree(proc.pid, 'SIGKILL'), 2000)
	}, timeout)

	// Read streams with caps while continuing to drain after the cap. This keeps
	// memory bounded even for noisy long-running commands.
	const stdoutPromise = processOutput.readLimited(proc.stdout, config.maxOutputBytes, '\n[… truncated]')
	const stderrPromise = processOutput.readLimited(proc.stderr, config.maxOutputBytes, '\n[… truncated]')
	const [stdout, stderrResult, code] = await Promise.all([stdoutPromise, stderrPromise, proc.exited])
	let out = stdout.text
	const stderr = stderrResult.text

	clearTimeout(timer)
	abortCleanup?.()

	// Build output string
	if (ctx.signal?.aborted) {
		return truncateOutput(out + (stderr ? '\n' + stderr : '') + '\n[interrupted]')
	}
	if (stderr) out += (out ? '\n' : '') + stderr
	if (code !== 0) out += `\n[exit ${code}]`
	out = appendCommitMetadata(out, command, ctx.cwd, code)

	return truncateOutput(out || '(no output)')
}

// ── Registration ──

const bashTool: Tool = {
	name: 'bash',
	description: 'Run a bash command. Output is captured and returned.',
	parameters: {
		command: { type: 'string', description: 'The bash command to execute' },
		timeout: { type: 'integer', description: 'Timeout in ms (default: 120000)' },
	},
	required: ['command'],
	execute,
}

function init(): void {
	toolRegistry.registerTool(bashTool)
}

export const bash = { config, stripCdCwd, killProcessTree, execute, init }
